# Generated by Django 4.0.4 on 2023-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment_quantity',
            field=models.IntegerField(default=0, verbose_name='Comments quantity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='news_quantity',
            field=models.IntegerField(default=0, verbose_name='News quantity'),
        ),
    ]
