# Generated by Django 4.0.4 on 2022-05-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
    ]
